# Generated by Django 3.0.8 on 2020-07-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200706_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countkeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=300)),
                ('count', models.IntegerField(max_length=5)),
            ],
        ),
    ]
