# Generated by Django 3.0.8 on 2020-07-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_countkeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countkeyword',
            name='count',
            field=models.IntegerField(),
        ),
    ]
