# Generated by Django 3.0.8 on 2020-07-08 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200708_0023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Countkeyword',
        ),
    ]
