# Generated by Django 3.0.8 on 2020-07-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_countkeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='searchresult',
            field=models.CharField(default='yes', max_length=200),
            preserve_default=False,
        ),
    ]
