# Generated by Django 3.0.8 on 2020-07-09 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_searchhistory_searchresult'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='searchhistory',
            table='search',
        ),
    ]
