# Generated by Django 3.0.8 on 2020-07-11 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200709_1234'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='searchhistory',
            table=None,
        ),
    ]
