# Generated by Django 3.0.8 on 2020-07-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200711_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='searchdate',
            field=models.DateTimeField(),
        ),
    ]
